version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: npm run lint

  propose_release_auto:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run release
  propose_release_prerelease:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run release -- --release-as=prerelease
  propose_release_patch:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run release -- --release-as=patch
  propose_release_minor:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run release -- --release-as=minor
  propose_release_major:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm run release -- --release-as=minor

  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: echo "build release assets"
  
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - run: echo "serverless deploy"
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release_auto:
          type: approval
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^master$/
      - release_prerelease:
          type: approval
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /^master$/
      - release_patch:
          type: approval
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^master$/
      - release_minor:
          type: approval
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^master$/
      - release_major:
          type: approval
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^master$/

      - propose_release_auto:
          requires:
            - release_auto
      - propose_release_prerelease:
          requires:
            - release_prerelease
      - propose_release_patch:
          requires:
            - release_patch
      - propose_release_minor:
          requires:
            - release_minor
      - propose_release_major:
          requires:
            - release_major

  release:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - manual_approval:
          type: approval
          requires:
            - release
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - manual_approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/